### PR TITLE
Import and Export User Widgets and other Goodies

### PR DESCRIPTION
**Pull request by thenewcoder**
So here is the first pass of the import and export functionality.
Try it out and let me know what you feel needs to be changed or added,
besides the users ability to properly handle name collisions.

I was thinking of maybe adding the choices: "overwrite, skip, ask" in the
file browser window as an option next.

Edit:
- I just added another big cleanup. I realized that I a lot of code was actually not needed anymore.
- I also changed the way the preview panel will decide which widget to display after deleting. Rather than just go back to the first one in the list each time, now it will display the widget that was next to it. Hopefully you agree with this change, as I found it more comfortable, especially when trying to delete a few test widgets.

### CODE REVIEW

**Comment by waylow** [comment]
Thanks for all the clean up work - I'm pretty sure that was some things I missed after editing the 'use selected object' so it didn't write to the user's temp folder.  (that wasn't my idea)

This looks pretty good but I did notice some things.

- First I love that it doesn't export a blank file if there are no widgets :)

- I tried to break it by having a broken file that it was importing and it just said "0 widgets imported".
I think this is good for now.   I don't think it needs specific feedback for "hey you idiot, you clearly messed with the json file to make it unuseable......so what do you expect from me!!"
But user feedback like "the name widget X already exists.....what do you want my to do?" would be awesome.

-It looks like the edges are tripled up when they are encoded into the user_widgets.json file.

- And I'm not sure if this needs to have it's own .bwl extension.
If it was just a json file extension then it would theoretically be more flexible.
It would be possible for someone to create a json file which ever way they saw fit.  (highly unlikely though haha)
But also, they could just rename the file and drop in in the folder and Blender should pick it up when it launches.  I think this would be more likely.

I also did a test by adding suzanne as a widget and then trying to open that .bwl file in gedit (my default text editor)
It couldn't handle it and just kept my fans whirring until I killed it.
I could open it in VSCodium though so I think the triple edges and high vertex count was pushing gedit to its limits.

I tested with a couple of cubes (with different names) and it opens fine.
I also tested importing the file that was crashing gedit and it worked as expected (even though the edges were tripled up)

**Comment by thenewcoder** [comment]
Thanks for the detailed feedback.
It's great that we are on different OSs and using different editors, as something that have no issues for me, might cause something on yours. :) 

I'll go through your feedback and see what changes and fixes I can make. In the meantime, could you send me a screenshot or the actual file of the user_widgets.json? I seem unable to locate what you are referring to.

Quick comment before I take a closer look:
Regarding the .bwl extension. Yeah, it's not needed or anything. Just wanted to play around with idea, cause it makes searching a whole lot easier and all that. No need to go through lots of files just to find it. More of a "convenience" than anything else. :)

**Comment by thenewcoder** [comment]
Oh, and regarding gedit being unable to open the json file. As you mentioned, because of the high vertex count. I've attempted to open text files in an editor before which almost crashed my computer, and then tried the same thing in another editor and it worked fine, albeit really slow to open. Maybe a good reason to use the .bwl. The file isn't supposed to be opened and messed with. Especially when a user exports a ton of widgets. ;) But edges being tripled up, doesn't sound good, although I can't seem to locate that issue... And shouldn't be something I caused...I think...since it's more or less using same code to write out as originally...

**Comment by waylow** [comment]
Oh I found how to replicate the triple edges.

If you add a shape that has faces - the edges get added 3 times.
If you add a shape without face - the edges are just added once.

**Comment by thenewcoder** [comment]
So, it's definitely not something I caused. :) But good catch!

Tried to replicate it.... maybe I'm doing something wrong...just got back from work short while ago, maybe my brain doesn't work.
So you mean, for example, if I add a cube, icosphere etc. to the widget library, edges will get added 3 times, no matter the shape as long as there are faces? You mean the actual "edges": [[1, 13], [2, 17]] etc will be duplicated 3 times for that widget? or you mean the data inside will be duplicated? "edges": [[1, 13], [1, 13], [1, 13]] ?  I did add an icosphere, and that example on the left got added 74 times. I haven't touched that part of the code before, where all the data is being stored form the shapes and so I don't know if that is how it needs to be or not.

**Comment by thenewcoder** [comment]
OK, I am just gonna come out and show my ignorance....But, how important is the face data for widgets when rigging? Is it needed? Or are all widgets used usually just verts and edges?
I added an icosphere without faces, and man, the differences in amount of saved data is huge!

**Comment by waylow** [comment]
Ok I think I found a solution.
That code doesn't need the if statement.  It can go straight to the edge calculation.
As it is at the moment, it loops through the edges on each face (if they exists) and then adds all those edges.

I'll update and commit to my main development branch

But yes - you are correct, it wasn't anything you did.  That's the first time I've looked at that part haha.
Been there since day dot.

**Comment by thenewcoder** [comment]
Great job! I'm still wondering about the faces, and how desired it is to save all that data!? What about asking the user if he wants/needs the face data? For example, a checkbox just below where you type the name of the new widget to be added!?

**Comment by waylow** [comment]
I think it was a bug since the start -- or it used to be handled differently back in 2.7

To me I think adding a checkbox is overkill.  People will make the shape, and add it.
Then they will realise that they shouldn't have added the faces, and have to delete it and do it again.

That will be the same if it's doing it again and checking the box, or doing it again after deleting the faces.

What about if any shape that was saved with faces, can be imported with OR without the faces?
Is that overthinking it?

**Comment by thenewcoder** [comment]
Probably a bug, maybe the original coder wasn't sure how to deal with the data, and then never got around to optimizing it. Either way, I'm going to check how much less data is being saved for the icosphere.

So you mean having an option in the import file browser to not import faces?
Or you mean when you click 'create' and add it to the bone, that it will take into account your preferences to use faces or not?

If the addon needs to save face data, then I guess your suggestion is sound.

**Comment by thenewcoder** [comment]
Huge differences to the icosphere! A major optimization right there!

**Pull request merged**
