### PR TITLE
User widgets now get their own separate json file

### PR DESCRIPTION
**Pull request by thenewcoder**
As the defaults and the user widgets are no longer friends, I've split them up
into separate files.  Not the prettiest code, but it gets the job done. Can be
refactored later to be a little bit more efficient.

### CODE REVIEW

**Comment by waylow** [comment]
Nice work :)

I'm working on the updated images for the docs - and while I'm doing that I'll create something for the 'missing' image.

**Comment by thenewcoder** [comment]
Is the ability to import/export the user widgets something you would want to have implemented now?

**Comment by waylow** [comment]
Not now, no.

But if you've run out of things to do - sure.

**Comment by thenewcoder** [comment]
I'll see if I will do it this week or wait until later. Just thought that perhaps it would be a nice way for someone to share their widgets. Or even just a way to transfer between computers. Although the export is basically just to copy the json file to a specified location.

**Pull request merged**
